### PR TITLE
Fix the header image in the README

### PR DESCRIPTION
**Pull request by wodin**

### CODE REVIEW

**Comment by amiller-gh** [comment]
@chriseppstein, we'll need a re-deploy of the website after this is pulled in. This will also break again if the asset ever changes without updating this hashed URL too – are we okay with that, or do we want a slightly more robust hosting solution for README assets?

**Comment by amiller-gh** [comment]
@wodin, mind updating in `src/packages/@css-blocks/core/README.md` too? 😄

**Comment by chriseppstein** [comment]
@amiller-gh Yeah, I thought webpack has things for this, I guess we're not webpacking right?

**Comment by amiller-gh** [comment]
No, we just build our typedoc site into our website's public directory right now – no webpacking involved, we treat it as a static asset.

**Comment by amiller-gh** [comment]
But, these image URLs also have to work on sites that scrape READMEs too, so we should use a resolvable URL in source: https://www.npmjs.com/package/@css-blocks/core

**Comment by wodin** [comment]
I've made the same change in packages/@css-blocks/core/README.md
I agree that the changes seem fragile given the hash in the filename, but thought I'd send in the PR and let you decide whether it was a good idea :)

**Comment by amiller-gh** [comment]
Merged 🎉 We'll get a longer term fix in for this later. We'll probably want to add our docs generation flow to the webpack build...

**Pull request merged**
